# Generated by Django 3.0.7 on 2020-06-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200606_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
