# Generated by Django 3.0.7 on 2020-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques',
            field=models.CharField(default='cool question', max_length=250),
            preserve_default=False,
        ),
    ]
