# Generated by Django 3.0.7 on 2020-06-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200625_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_slug',
            field=models.SlugField(unique=True),
        ),
    ]
